# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/92/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/92/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ivan/CLionProjects/Data_Structures

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ivan/CLionProjects/Data_Structures

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/92/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/92/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivan/CLionProjects/Data_Structures/CMakeFiles /home/ivan/CLionProjects/Data_Structures/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivan/CLionProjects/Data_Structures/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Data_Structures

# Build rule for target.
Data_Structures: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Data_Structures
.PHONY : Data_Structures

# fast build rule for target.
Data_Structures/fast:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/build
.PHONY : Data_Structures/fast

DisjoinSet.o: DisjoinSet.cpp.o

.PHONY : DisjoinSet.o

# target to build an object file
DisjoinSet.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/DisjoinSet.cpp.o
.PHONY : DisjoinSet.cpp.o

DisjoinSet.i: DisjoinSet.cpp.i

.PHONY : DisjoinSet.i

# target to preprocess a source file
DisjoinSet.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/DisjoinSet.cpp.i
.PHONY : DisjoinSet.cpp.i

DisjoinSet.s: DisjoinSet.cpp.s

.PHONY : DisjoinSet.s

# target to generate assembly for a file
DisjoinSet.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/DisjoinSet.cpp.s
.PHONY : DisjoinSet.cpp.s

List.o: List.cpp.o

.PHONY : List.o

# target to build an object file
List.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/List.cpp.o
.PHONY : List.cpp.o

List.i: List.cpp.i

.PHONY : List.i

# target to preprocess a source file
List.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/List.cpp.i
.PHONY : List.cpp.i

List.s: List.cpp.s

.PHONY : List.s

# target to generate assembly for a file
List.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/List.cpp.s
.PHONY : List.cpp.s

Queue.o: Queue.cpp.o

.PHONY : Queue.o

# target to build an object file
Queue.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/Queue.cpp.o
.PHONY : Queue.cpp.o

Queue.i: Queue.cpp.i

.PHONY : Queue.i

# target to preprocess a source file
Queue.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/Queue.cpp.i
.PHONY : Queue.cpp.i

Queue.s: Queue.cpp.s

.PHONY : Queue.s

# target to generate assembly for a file
Queue.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/Queue.cpp.s
.PHONY : Queue.cpp.s

Stack.o: Stack.cpp.o

.PHONY : Stack.o

# target to build an object file
Stack.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/Stack.cpp.o
.PHONY : Stack.cpp.o

Stack.i: Stack.cpp.i

.PHONY : Stack.i

# target to preprocess a source file
Stack.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/Stack.cpp.i
.PHONY : Stack.cpp.i

Stack.s: Stack.cpp.s

.PHONY : Stack.s

# target to generate assembly for a file
Stack.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/Stack.cpp.s
.PHONY : Stack.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Data_Structures.dir/build.make CMakeFiles/Data_Structures.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Data_Structures"
	@echo "... edit_cache"
	@echo "... DisjoinSet.o"
	@echo "... DisjoinSet.i"
	@echo "... DisjoinSet.s"
	@echo "... List.o"
	@echo "... List.i"
	@echo "... List.s"
	@echo "... Queue.o"
	@echo "... Queue.i"
	@echo "... Queue.s"
	@echo "... Stack.o"
	@echo "... Stack.i"
	@echo "... Stack.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

